- id: "1618637076003"
  alias: DeepStack Scan Cameras
  description: Scan All Camera
  mode: restart
  variables:
    start_scan_time: now()
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: automation.deepstack_scan_cameras
      to: "on"
  condition: []
  action:
    - service: input_text.set_value
      data:
        value: "{{ now() }}"
      target:
        entity_id: input_text.scan_start_time
    - service: image_processing.scan
      data: {}
      target:
        entity_id:
          - image_processing.camera_1
          - image_processing.camera_2
          - image_processing.camera_5
          - image_processing.camera_6
          - image_processing.e43460774
          - image_processing.e73655823
    - service: input_text.set_value
      data:
        value: "{{ (as_timestamp(now()) - as_timestamp(states.input_text.scan_start_time.state)) | float }} "
      target:
        entity_id: input_text.scan_duration
    - service: system_log.write
      data:
        level: warning
        message: "Scan Take  {{ states.input_text.scan_duration.state | round(2) }} seconds"
    - service: automation.trigger
      target:
        entity_id: automation.deepstack_scan_cameras
