# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
homeassistant:
  allowlist_external_dirs:
    - /config/www
    - /media
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 9
  unit_system: metric
  time_zone: Asia/Ho_Chi_Minh
  name: JETSON NANO
  customize: !include customize.yaml
  external_url: !secret external_url
  internal_url: !secret internal_url
# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
camera: !include cameras.yaml
group: !include groups.yaml
image_processing: !include image_processings.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml

ffmpeg:

input_boolean:
  scan_camera_1:
    name: Scan Camera 1
    icon: mdi:webcam
    initial: true
  scan_camera_2:
    name: Scan Camera 2
    icon: mdi:webcam
    initial: true
  scan_camera_3:
    name: Scan Camera 3
    icon: mdi:webcam
    initial: true
  scan_camera_4:
    name: Scan Camera 4
    icon: mdi:webcam
    initial: true
  scan_camera_5:
    name: Scan Camera 5
    icon: mdi:webcam
    initial: true
  scan_camera_6:
    name: Scan Camera 6
    icon: mdi:webcam
    initial: true
  scan_e43460774:
    name: Scan E43460774
    icon: mdi:webcam
    initial: true
  scan_e73655823:
    name: Scan E73655823
    icon: mdi:webcam
    initial: true

input_text:
  scan_start_time:
    name: Scan Start Time
  scan_duration:
    name: Scan Duration
logger:
  default: WARNING

stream:
