- platform: deepstack_object
  ip_address: 192.168.1.122
  port: 80
  # api_key: mysecretkey
  # custom_model: mask
  # confidence: 80
  # save_file_folder: /config/www/object/
  save_file_format: jpg
  save_timestamped_file: False
  always_save_latest_file: False
  scale: 1
  # roi_x_min: 0.35
  # roi_x_max: 0.8
  #roi_y_min: 0.4
  # roi_y_max: 0.8
  targets:
    - target: person
      confidence: 50
  source:
    - entity_id: camera.camera_1_low
      name: camera_1

- platform: deepstack_object
  ip_address: 192.168.1.122
  port: 80
  # api_key: mysecretkey
  # custom_model: mask
  # confidence: 80
  # save_file_folder: /config/www/object/
  save_file_format: jpg
  save_timestamped_file: False
  always_save_latest_file: False
  scale: 1
  # roi_x_min: 0.35
  # roi_x_max: 0.8
  #roi_y_min: 0.4
  # roi_y_max: 0.8
  targets:
    - target: person
      confidence: 50
  source:
    - entity_id: camera.camera_2_low
      name: camera_2

- platform: deepstack_object
  ip_address: 192.168.1.122
  port: 80
  # api_key: mysecretkey
  # custom_model: mask
  # confidence: 80
  # save_file_folder: /config/www/object/
  save_file_format: jpg
  save_timestamped_file: False
  always_save_latest_file: False
  scale: 1
  # roi_x_min: 0.35
  # roi_x_max: 0.8
  #roi_y_min: 0.4
  # roi_y_max: 0.8
  targets:
    - target: person
      confidence: 50
  source:
    - entity_id: camera.camera_5_low
      name: camera_5

- platform: deepstack_object
  ip_address: 192.168.1.122
  port: 80
  # api_key: mysecretkey
  # custom_model: mask
  # confidence: 80
  # save_file_folder: /config/www/object/
  save_file_format: jpg
  save_timestamped_file: False
  always_save_latest_file: False
  scale: 1
  # roi_x_min: 0.35
  # roi_x_max: 0.8
  #roi_y_min: 0.4
  # roi_y_max: 0.8
  targets:
    - target: person
      confidence: 50
  source:
    - entity_id: camera.camera_6_low
      name: camera_6

- platform: deepstack_object
  ip_address: 192.168.1.122
  port: 80
  # api_key: mysecretkey
  # custom_model: mask
  # confidence: 80
  # save_file_folder: /config/www/object/
  save_file_format: jpg
  save_timestamped_file: False
  always_save_latest_file: False
  scale: 1
  # roi_x_min: 0.35
  # roi_x_max: 0.8
  #roi_y_min: 0.4
  # roi_y_max: 0.8
  targets:
    - target: person
      confidence: 50
  source:
    - entity_id: camera.e43460774_low
      name: e43460774

- platform: deepstack_object
  ip_address: 192.168.1.122
  port: 80
  # api_key: mysecretkey
  # custom_model: mask
  # confidence: 80
  # save_file_folder: /config/www/object/
  save_file_format: jpg
  save_timestamped_file: False
  always_save_latest_file: False
  scale: 1
  # roi_x_min: 0.35
  # roi_x_max: 0.8
  #roi_y_min: 0.4
  # roi_y_max: 0.8
  targets:
    - target: person
      confidence: 50
  source:
    - entity_id: camera.e73655823_low
      name: e73655823
